### PR TITLE
added base UI of diary page

### PR DESCRIPTION
**Pull request by jaisonjoshi**
@AnandBaburajan added the base UI of dairy page. please review the pr.

### CODE REVIEW

**Comment by anandbaburajan** [comment]
@jaisonjoshi Hey, why did you close the PR? Should I still review this?

**Comment by jaisonjoshi** [comment]
@AnandBaburajan The code climate showed an error that the function has exceeded the number of lines.

**Comment by jaisonjoshi** [comment]
I thought it would affect the pr...

**Comment by anandbaburajan** [comment]
> The code climate showed an error that the function has exceeded the number of lines.

That's okay! It's not that huge of an error and you can just push another commit if you want to fix it. It's just a suggestion from CodeClimate that it would be better if your function was shorter (for readability, maintainability, etc)

**Comment by anandbaburajan** [comment]
@jaisonjoshi Did you delete your forked repository? We could have simply re-opened this PR. Please let me know your issues and doubts at the chatroom. :)

**Comment by jaisonjoshi** [comment]
i just edited my function ..but somehow I couldn't commit again... so i forked it again..

**Comment by anandbaburajan** [comment]
> i just edited my function ..but somehow I couldn't commit again... so i forked it again..

Did you look into why you couldn't commit again? If you've doubts, feel free to let us know in the group and please try not to delete the forked repos if there are workarounds. :)

**Comment by jaisonjoshi** [comment]
okay ..I think it is because of whitespaces and after cleared and tried to commit, it says it is upto date...

**Comment by jaisonjoshi** [comment]
i made another pull request and code climate error again appeared.. there is still 31 lines.. :(

**Comment by anandbaburajan** [comment]
> i made another pull request and code climate error again appeared.. there is still 31 lines.. :(

That's okay because the difference (31 - 25) is not that huge

**Pull request closed without merging**
